apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - ingress.yaml

images:
  - name: us-central1-docker.pkg.dev/my-gcp-project/my-registry/sample-app
    newTag: v1.0.0 # overwritten automatically by cloudbuild.yaml on every build

configMapGenerator:
  - name: sample-app-config
    behavior: merge
    literals:
      - log-level=DEBUG

replicas:
  - name: sample-app
    count: 1
